/* ===== GCI DATA · PART 4 — 라이선스 IP + 미공개 ===== */

const G4 = [
{
 id:"gc", no:"10", name:"일곱 개의 대죄: GRAND CROSS", short:"7DS GRAND CROSS",
 ipClass:"LICENSED", genre:"수집형 카드배틀 RPG", status:"LIVE", maturity:"HIGH",
 dev:"넷마블F&C", release:"2019.06.04 (한·일) / 2020.03.03 (글로벌)", plat:"모바일", region:"글로벌",
 sw:["#FFD84D","#E8503A","#3FA9E8","#5FBF6A"],
 asset:"CHARACTER", assetNote:"캐릭터 + 콜라보. 7년차 라이브에서 화제를 만드는 것은 콜라보 참전",
 one:"원작 스토리를 애니메이션 컷신으로 다시 보며 스킬 카드를 조합해 싸우는 7년차 수집형 RPG.",
 coreFantasy:{code:"REUNION WITH THE STORY", flow:["원작","재현","수집","조합","참전"],
   desc:"7년을 지탱한 힘은 액션이 아니라 <b>재현도</b>다. 애니메이션 품질 컷신과 원작자 검수를 거친 캐릭터 구현이 팬을 붙잡았다. 크리에이티브도 \"원작이 여기 있다\"로 간다."},
 iconic5:[
  ["애니메이션 컷신","SCENE","이 게임 최대 강점이자 최고의 광고 소재","★★★★★"],
  ["일곱 대죄의 문장","SYMBOL","짐승 문양. 캐릭터 식별의 핵심","★★★★★"],
  ["카드 랭크업 → 필살","SYSTEM","장르를 3초에 설명하는 화면","★★★★☆"],
  ["밝은 소년만화 톤","COLOR","고채도 셀 애니. 다크화가 최대 사고","★★★★☆"],
  ["콜라보 참전","SYMBOL","Re:제로·가치아쿠타 등 정기적 축제","★★★★☆"]],
 heat:[
  {n:"멜리오다스", role:"기사단장 · 분노의 죄", heat:"★★★★★", vis:"★★★★★", ua:"★★★★★", sns:"★★★★☆",
   why:"원작 주인공. 소년 외형이나 최소 3,000살 이상. 가벼운 태도와 진심일 때의 격차가 팬 반응 지점",
   scene:"부러진 검을 어깨에 걸친 모습", rel:"엘리자베스와 영겁의 윤회",
   line:"NOT ENOUGH PUBLIC DATA", nick:"NOT ENOUGH PUBLIC DATA", now:"뽑기 연출에 등장하는 대표 캐릭터",
   basis:"OFFICIAL — 원작 주인공, 공식 연출 전면 배치"},
  {n:"엘리자베스", role:"리오네스 제3왕녀", heat:"★★★★★", vis:"★★★★★", ua:"★★★★☆", sns:"★★★★☆",
   why:"영겁의 윤회로 환생을 반복하는 존재. IP의 정서적 심장",
   scene:"멜리오다스와의 재회", rel:"⚠ 멜리오다스와의 관계 — 각색 절대 금지",
   line:"NOT ENOUGH PUBLIC DATA", nick:"—", now:"—", basis:"OFFICIAL — 원작 히로인"},
  {n:"일곱 대죄 멤버 6인", role:"기사단", heat:"★★★★☆", vis:"★★★★☆", ua:"★★★★☆", sns:"★★★☆☆",
   why:"각자 다른 죄와 종족. 체구·능력이 모두 달라 실루엣 다양성이 크다",
   scene:"전원 집결", rel:"죄인으로 낙인찍혀 흩어졌다가 재집결", line:"—", nick:"—",
   now:"⚠ 개별 설정 공식 확인 필요", basis:"OFFICIAL — 원작 구성. 개별 상세 미확보"},
  {n:"콜라보 캐릭터", role:"기간 한정", heat:"★★★★☆", vis:"★★★★☆", ua:"★★★★★", sns:"★★★★★",
   why:"⭐ 타 IP 팬 유입의 최대 창구. 2026년만 Re:제로(4월)·가치아쿠타(6월)",
   scene:"참전 발표", rel:"—", line:"—", nick:"—",
   now:"현 시점 신규 유입 1순위 · ⚠ 콜라보사별 IP 가이드 별도",
   basis:"OFFICIAL — 2026 콜라보 보도자료 다수"}],
 vdna:[
  ["애니메이션 컷신","원작이 여기 있다","몰입 · 만족","⭐ 이 게임은 컷신 자체가 광고 소재. 별도 제작보다 컷신 활용이 효율적"],
  ["일곱 대죄 문장","각자의 죄를 짊어진 표식","소속 · 식별","캐릭터 없이 캐릭터를 이야기하는 오브젝트. 형태 오류 빈발 영역"],
  ["고채도 원색 + 셀 애니","밝은 소년만화","유쾌 · 동료애","⭐ 사내 MMORPG 문법을 가져오면 IP가 붕괴한다"],
  ["카드 3장 → 필살","전략이 맞아떨어지는 순간","쾌감","장르 오인 방지 장치. 액션처럼 보이면 설치 후 이탈"],
  ["캐릭터별 상징색","종족·체구가 모두 다르다","다양성","실루엣만으로 구분되는 라인업이 이 IP의 자산"]],
 fanLang:[
  {t:"7DS", risk:"safe", origin:"국제 통용 약칭", when:"원작 애니메이션 확산기",
   why:"Seven Deadly Sins의 축약", now:"글로벌 표준 약칭", use:"글로벌 채널 자유 사용", src:"COMMUNITY SIGNAL"},
  {t:"필살", risk:"safe", origin:"카드 조합의 최종 기술 공식 명칭", when:"출시 시점",
   why:"게임 고유 전투 문법", now:"상시", use:"장르를 설명하는 단어", src:"OFFICIAL"},
  {t:"섬멸전", risk:"safe", origin:"실시간 협력 콘텐츠 공식 명칭", when:"—", why:"—",
   now:"대표 협력 콘텐츠", use:"자유 사용", src:"OFFICIAL"},
  {t:"○○가 참전한다", risk:"safe", origin:"콜라보 발표의 정형 포맷", when:"콜라보 운영 축적기",
   why:"타 IP 팬에게 즉시 이해되는 구조", now:"⭐ 매 콜라보마다 재사용 가능한 캠페인 템플릿",
   use:"콜라보사 IP 가이드 준수 조건", src:"OFFICIAL"},
  {t:"777", risk:"safe", origin:"7,777만 다운로드 · 777 릴레이 캠페인", when:"2026.01~06 캠페인",
   why:"숫자 7이 타이틀 고유 상징으로 정착", now:"브랜딩 자산", use:"자유 사용", src:"OFFICIAL"}],
 landmine:[
  {t:"다크 판타지 톤", lv:"CRITICAL", d:"IP 정체성 정반대",
   why:"⭐ 사내 MMORPG 문법을 그대로 가져오면 실패한다. 원작 팬 즉시 이탈", src:"OFFICIAL"},
  {t:"멜리오다스–엘리자베스 관계 각색", lv:"CRITICAL", d:"영겁의 윤회 설정 위에 선 관계",
   why:"원작자 검수 IP. 이 IP 최대 지뢰", src:"OFFICIAL"},
  {t:"액션 RPG처럼 보이게 연출", lv:"HIGH", d:"실제로는 카드 전략 게임",
   why:"장르 오인 → 설치 후 즉시 이탈. 카드·턴제 요소를 반드시 노출", src:"OFFICIAL"},
  {t:"신규 혜택만 강조", lv:"MEDIUM", d:"7년차 잔류 유저의 상대적 박탈감",
   why:"신규·기존 소구를 채널별로 분리해야 한다", src:"COMMUNITY SIGNAL"},
  {t:"자매작 Origin과 소재 혼용", lv:"HIGH", d:"같은 IP·같은 개발사·비슷한 이름",
   why:"⭐ 제작 단계에서 소재를 물리적으로 분리. GC는 카드 UI를 반드시 넣는다", src:"OFFICIAL"},
  {t:"콜라보 캐릭터를 본편처럼 표기", lv:"HIGH", d:"콜라보사 IP 권리 영역",
   why:"기간 한정임을 명시하지 않으면 권리 문제", src:"OFFICIAL"}],
 origIP:{
  memory:"스즈키 나카바 만화 「일곱 개의 대죄」. 브리타니아 대륙, 다섯 종족(인간·여신족·마신족·요정족·거인족). 성기사가 왕국을 장악하자 리오네스 제3왕녀 엘리자베스가 죄인으로 몰린 전설의 기사단을 찾아 나선다. <b>죄인이라 불린 자들이 실제로는 왕국을 지킨다</b>는 낙인의 역전 구조.",
  game:"원작 스토리를 애니메이션 품질 컷신으로 재현. 스킬 카드 랭크업 전투. 원작에 전투 묘사가 없던 캐릭터는 게임이 스킬을 새로 설계. 섬멸전·마수전·마신왕전 등 콘텐츠.",
  gap:"원작자와 교류가 활발하며 검수를 받는다. 팬의 기준이 높다.",
  sens:"멜리오다스–엘리자베스의 영겁의 윤회 관계. 각 대죄 멤버의 문장과 상징색.",
  rights:"원작사 IP 가이드 + 콜라보사별 가이드 미확보 — RIGHTS CHECK REQUIRED"},
 timeline:[
  {d:"2019.06.04", e:"한국·일본 출시", fan:"—", mkt:"—", hot:false},
  {d:"2020.03.03", e:"글로벌 출시", fan:"—", mkt:"—", hot:false},
  {d:"누적", e:"매출 10억 달러 돌파", fan:"다운로드 7,777만+", mkt:"넷마블을 글로벌 퍼블리셔 매출 10위권에 올린 타이틀", hot:true},
  {d:"2026.01~06", e:"777 릴레이 캠페인", fan:"7개월 장기 캠페인", mkt:"'7'을 브랜딩 자산으로 활용한 사례", hot:false},
  {d:"2026.04", e:"Re:제로 콜라보", fan:"SSR 스바루&베아트리스·에밀리아·프리실라", mkt:"타 IP 팬 유입", hot:true},
  {d:"2026.06", e:"가치아쿠타 콜라보", fan:"SSR 팀 아쿠타 4종", mkt:"⭐ 콜라보가 7년차 라이브의 정기 화제 장치", hot:true}],
 mktHistory:"777 릴레이 캠페인(2026.01~06, 7개월) 확인. 그 외 UA·브랜드 필름 사례는 NOT ENOUGH PUBLIC DATA",
 starter:{
  ua:{char:"멜리오다스 / 콜라보 캐릭터", hook:"○○가 참전한다 — 콜라보 발표 정형 포맷",
   sit:"콜라보 캐릭터 등장", world:"브리타니아", fantasy:"REUNION WITH THE STORY",
   sec3:"카드 3장이 합쳐지며 필살기로 이어지는 리듬", avoid:"다크 톤 / 액션 RPG 오인 / 관계 각색"},
  banner:{hero:"멜리오다스 또는 콜라보 캐릭터", sym:"일곱 대죄 문장", copy:"동료 · 죄 · 문장 · 필살 · 참전",
   bg:"브리타니아 초원·왕국", trigger:"고채도 셀 애니 톤"},
  sns:{meme:"원작 유머 톤 기반 캐릭터 대사 밈", rel:"대죄 7인의 동료 관계",
   lang:"7DS · 필살 · 참전 · 777", idea:"최애 대죄 투표 / 콜라보 예측"},
  promo:{hero:"대죄 전원 집결", world:"다섯 종족과 브리타니아", motif:"문장이 하나씩 켜지는 인터랙션",
   scroll:"수배서 → 진실의 역전", motion:"카드 합성"},
  ai:{keep:"밝은 채도 애니 톤 · 중세 판타지 시대성 · 문장 형태", char:"⛔ 원작 캐릭터 생성 비권장 — 원작자 검수 IP",
   world:"브리타니아 풍경·왕국·요정왕의 숲 — AI 배경 적합", avoid:"사실주의 렌더링 · 다크 톤 · 현대/SF 요소"}},
 sources:[["공식 사이트 7ds.netmarble.com","OFFICIAL"],["공식 유튜브","OFFICIAL"],
  ["Sensor Tower — 누적 매출 10억 달러","MEDIA"],["경향게임스 — 가치아쿠타 콜라보","MEDIA"],
  ["경기신문·시사뉴스 — Re:제로 콜라보","MEDIA"],["루리웹 — 777 릴레이 캠페인","MEDIA"],
  ["나무위키 — 시스템·원작자 검수","COMMUNITY SIGNAL"]],
 gaps:["일곱 대죄 멤버 6인의 개별 설정 (죄·종족·상징색·무기)","ICONIC LINES — 원작 명대사 미조사","콜라보사별 IP 표현 제약","원작 애니메이션 영상 사용권","7년차 유저 구성·신규 유입 경로"]
},

{
 id:"origin", no:"11", name:"일곱 개의 대죄: Origin", short:"7DS Origin",
 ipClass:"LICENSED_EXP", genre:"오픈월드 액션 RPG", status:"LIVE", maturity:"MEDIUM",
 dev:"넷마블F&C", release:"2026.03.17 (PS5·Steam) / 03.24 (모바일)", plat:"PS5 · Steam · 모바일", region:"글로벌",
 sw:["#5BA84F","#6FC3E8","#E8C04A","#C97B4A"],
 asset:"WORLD", assetNote:"⭐ 캐릭터가 아니라 공간이 자산. 광고는 '이동'을 팔아야 한다",
 one:"멜리오다스의 아들 트리스탄이 되어 뒤틀린 브리타니아 대륙을 직접 걷는 오픈월드 액션 RPG.",
 coreFantasy:{code:"EXPLORATION", flow:["계승","출발","탐험","발견","회복"],
   desc:"유일한 차별점은 <b>브리타니아를 직접 이동한다</b>는 것이다. GRAND CROSS가 <i>보는 게임</i>이라면 Origin은 <i>걷는 게임</i>이다. 콘솔·PC까지 나온 이유가 여기에 있다."},
 iconic5:[
  ["대륙 원경 리빌","SCENE","언덕을 넘자 펼쳐지는 전경","★★★★★"],
  ["찢어진 하늘","SYMBOL","별의 서 폭주로 왜곡된 시공간","★★★★☆"],
  ["모닥불 요리","SCENE","경쟁작 광고에 없는 소재","★★★★☆"],
  ["트리스탄","CHARACTER","멜리오다스와 엘리자베스의 아들. 네피림","★★★★☆"],
  ["초원 녹색 · 하늘 청색","COLOR","시간대 변화를 적극 활용","★★★☆☆"]],
 heat:[
  {n:"트리스탄 리오네스", role:"주인공 · 플레이어", heat:"★★★★☆", vis:"★★★★★", ua:"★★★★★", sns:"★★★★☆",
   why:"마신족 아버지와 인간으로 환생한 여신족 어머니 사이의 네피림. 전설의 자식이라는 위치",
   scene:"언덕 위에서 대륙을 내려다보는 순간", rel:"멜리오다스·엘리자베스의 아들",
   line:"NOT ENOUGH PUBLIC DATA", nick:"—",
   now:"⚠ 완성형 강자로 묘사하면 성장 서사 소실. 멜리오다스 복제로 보이면 안 된다",
   basis:"OFFICIAL — 공식 소개가 주인공으로 명시"},
  {n:"멜리오다스 · 엘리자베스", role:"부모 세대", heat:"★★★★★", vis:"★★★★★", ua:"NOT ENOUGH PUBLIC DATA", sns:"NOT ENOUGH PUBLIC DATA",
   why:"원작 주인공. 인지도는 최상위", scene:"—", rel:"트리스탄의 부모", line:"—", nick:"—",
   now:"⚠ 게임 내 등장 범위 미확인 — 확인 전 크리에이티브 사용 금지",
   basis:"UNVERIFIED — 게임 내 비중 확인 못 함"},
  {n:"동료들", role:"파티", heat:"NOT ENOUGH PUBLIC DATA", vis:"NOT ENOUGH PUBLIC DATA", ua:"NOT ENOUGH PUBLIC DATA", sns:"NOT ENOUGH PUBLIC DATA",
   why:"트리스탄과 함께 대륙을 탐험", scene:"—", rel:"—", line:"—", nick:"—",
   now:"⚠ 구성 공식 확인 필요", basis:"UNVERIFIED"},
  {n:"고서", role:"신규 영웅", heat:"NOT ENOUGH PUBLIC DATA", vis:"NOT ENOUGH PUBLIC DATA", ua:"NOT ENOUGH PUBLIC DATA", sns:"NOT ENOUGH PUBLIC DATA",
   why:"업데이트로 추가", scene:"—", rel:"—", line:"—", nick:"—",
   now:"⚠ 설정 미확인", basis:"MEDIA — 이름만 확인"}],
 vdna:[
  ["원경 와이드","대륙이 눈앞에 펼쳐진다","해방 · 기대","⭐ 이 게임의 카메라 문법. 폐쇄 던전 위주 화면은 정체성 상실"],
  ["찢어진 하늘","별의 서가 폭주했다","불안 · 사명","지역마다 다른 형태의 왜곡. 사건의 규모를 시각화"],
  ["시간대 변화","오픈월드의 호흡","여유 · 몰입","일출·석양 활용. AI 배경 변주에 최적"],
  ["생활 콘텐츠","싸움만 하지 않는다","여유 · 생활감","⭐ 모닥불 요리·낚시. 액션 RPG 광고에 없는 소재라 기억에 남는다"],
  ["밝은 자연색","원작 톤 계승","모험 · 활기","다크 톤 금지. GRAND CROSS와 같은 IP 톤"]],
 fanLang:[
  {t:"Origin / 오리진", risk:"safe", origin:"GRAND CROSS와 구분하는 호칭", when:"출시 시점",
   why:"같은 IP의 두 게임을 구분할 필요", now:"⚠ 자매작과 혼동되지 않도록 표기 통일 필요",
   use:"타이틀 표기 시 항상 풀네임 권장", src:"OFFICIAL"},
  {t:"트리스탄", risk:"safe", origin:"주인공 이름", when:"원작 「묵시록의 4기사」 계보",
   why:"—", now:"상시", use:"자유 사용", src:"OFFICIAL"},
  {t:"별의 서", risk:"safe", origin:"사건의 원인이 된 물건", when:"출시 시점",
   why:"게임 오리지널 스토리의 발단", now:"상시", use:"세계관 어휘로 사용 가능", src:"OFFICIAL"}],
 landmine:[
  {t:"GRAND CROSS와 혼동되는 연출", lv:"CRITICAL", d:"같은 IP·같은 개발사·비슷한 이름",
   why:"⭐ 카드 UI 절대 금지. 오픈월드 이동을 반드시 노출해야 갈린다", src:"OFFICIAL"},
  {t:"다크 판타지 톤", lv:"HIGH", d:"IP 정체성 정반대", why:"원작 팬 즉시 이탈", src:"OFFICIAL"},
  {t:"트리스탄을 멜리오다스처럼 묘사", lv:"HIGH", d:"캐릭터 독립성 훼손",
   why:"성장기 인물로. 부모와의 차이를 살려야 한다", src:"OFFICIAL"},
  {t:"부모 세대 등장 범위 임의 확대", lv:"HIGH", d:"게임 내 실제 비중 미확인",
   why:"확인 전까지 트리스탄 중심으로 구성", src:"UNVERIFIED"},
  {t:"폐쇄 던전 위주 화면", lv:"MEDIUM", d:"오픈월드 정체성 상실",
   why:"원경·하늘·이동을 반드시 포함", src:"OFFICIAL"},
  {t:"모바일 게임처럼만 보이는 연출", lv:"MEDIUM", d:"PS5·Steam 유저 이탈",
   why:"플랫폼별 소재 분리 필요. 콘솔용은 그래픽·스케일 강조", src:"OFFICIAL"}],
 origIP:{
  memory:"「일곱 개의 대죄」 + 공식 후속작 「묵시록의 4기사」(동일 작가 스즈키 나카바). 브리타니아 대륙, 다섯 종족, 멜리오다스와 엘리자베스의 서사.",
  game:"시점은 「7대죄」 완결 이후 ~ 「묵시록의 4기사」 이전. <b>스토리는 게임 오리지널</b>이며 멀티버스 세계관으로 전개. 별의 서 폭주로 시공간이 뒤틀린 대륙을 되돌린다. 오픈월드 탐험 + 낚시·요리 생활 콘텐츠.",
  gap:"⭐ 넷마블 공식 포지셔닝은 \"원작을 몰라도 자연스럽게 녹아들 만큼 강한 몰입감\" — 신규 유저 진입을 명시적으로 겨냥한 설계. 원작 팬 소구와 신규 소구를 분리할 근거.",
  sens:"트리스탄의 네피림 정체성. 부모 세대의 등장 범위. 브리타니아 지명·지리.",
  rights:"원작사 IP 가이드 미확보 — RIGHTS CHECK REQUIRED"},
 timeline:[
  {d:"원작", e:"「7대죄」 → 「묵시록의 4기사」", fan:"동일 작가의 공식 후속작 계보", mkt:"Origin은 두 작품 사이를 메운다", hot:false},
  {d:"2025", e:"TGS 빌드 공개", fan:"—", mkt:"출시 전 소개", hot:false},
  {d:"2026.03.17", e:"PS5·Steam 선공개", fan:"—", mkt:"콘솔·PC 우선 전략", hot:true},
  {d:"2026.03.24", e:"모바일 정식 출시", fan:"—", mkt:"⭐ 크로스플랫폼 서비스 본격화 — 플랫폼별 소재 분리 필요", hot:true},
  {d:"—", e:"신규 영웅 '고서' 추가", fan:"—", mkt:"운영 진행 확인", hot:false}],
 mktHistory:"NOT ENOUGH PUBLIC DATA — 출시 5개월차, 캠페인 사례 미조사",
 starter:{
  ua:{char:"트리스탄", hook:"언덕을 넘으면 — 오르는 동안 화면을 막았다가 정상에서 대륙 전경을 여는 단 한 번의 리빌",
   sit:"미개척 지역 진입", world:"뒤틀린 브리타니아", fantasy:"EXPLORATION",
   sec3:"시야를 막던 언덕이 사라지고 대륙이 펼쳐짐", avoid:"카드 UI / 다크 톤 / 폐쇄 던전 위주"},
  banner:{hero:"트리스탄", sym:"찢어진 하늘", copy:"대륙 · 탐험 · 계승 · 여정 · 별의 서",
   bg:"초원과 하늘", trigger:"원경 와이드"},
  sns:{meme:"⭐ \"낚시하는 계승자\" — 세계를 구하러 가는 인물이 강가에 앉아 낚시만 한다",
   rel:"트리스탄 ↔ 동료", lang:"오리진 · 트리스탄 · 별의 서", idea:"오늘의 요리 공유"},
  promo:{hero:"언덕 위에서 본 대륙 전경", world:"브리타니아 지역별 랜드마크", motif:"스크롤에 따라 대륙이 열림",
   scroll:"서쪽 끝 → 동쪽 끝 종주", motion:"시간대 전환(일출→석양)"},
  ai:{keep:"밝은 채도 애니 톤 · 중세 판타지 시대성 · 원경 구도", char:"⛔ 트리스탄 등 원작 캐릭터 생성 비권장",
   world:"⭐ 대륙 풍경·초원·호수·산맥 — AI 효율 최상. 시간대 변주에 최적", avoid:"사실주의 렌더링 · 다크 톤 · 폐쇄 공간 위주"}},
 sources:[["공식 사이트 origin.netmarble.com","OFFICIAL"],["Steam 스토어 페이지","OFFICIAL"],
  ["공식 유튜브 @7ds_origin_kr","OFFICIAL"],["서울와이어·주간한국 — 출시 정보","MEDIA"],
  ["뉴데일리 — 원작에 대한 헌사 리뷰","MEDIA"],["나무위키 — 시점·게임 오리지널 스토리","COMMUNITY SIGNAL"],
  ["나무위키 — 트리스탄 리오네스(네피림)","COMMUNITY SIGNAL"]],
 gaps:["동료 캐릭터 구성","부모 세대 게임 내 등장 범위 (크리에이티브 사용 범위 결정에 필수)","게임 내 실제 지역 구성","크로스플랫폼 계정 연동 사양","ICONIC LINES — 미조사","MARKETING HISTORY — 미조사","출시 후 유저 반응 데이터"]
},

{
 id:"got", no:"12", name:"왕좌의 게임: 킹스로드", short:"GoT 킹스로드",
 ipClass:"LICENSED_EXP", genre:"오픈월드 스토리 액션 RPG", status:"LIVE", maturity:"HIGH",
 dev:"넷마블네오", release:"2026.05.14 (PC) / 05.21 (모바일)", plat:"PC(Steam) · 모바일", region:"글로벌",
 sw:["#3A3F44","#6B6259","#A89B84","#E8E4DC"],
 asset:"WORLD", assetNote:"드라마가 만든 공간이 자산. 단 인물은 배우 초상권으로 막혀 있다",
 one:"드라마 시즌4 시점의 웨스테로스에서 몰락한 기사 가문의 서자가 되어 대륙을 직접 걷는 액션 RPG.",
 coreFantasy:{code:"BELONGING TO THE WORLD", flow:["몰락","서자","맹세","재건","명예"],
   desc:"원작 명장면을 다시 보여주지 않는다. 존 스노우가 장벽 너머 위협을 발견했을 때 <b>누가 그것을 먼저 알렸는지</b> — 드라마가 다루지 않은 이면을 오리지널 스토리로 채웠다. 플레이어는 관객이 아니라 빈칸을 메우는 인물이다."},
 iconic5:[
  ["웨스테로스 지형","WORLD","북부의 눈, 남부의 성채. 드라마 팬이 알아보는 공간","★★★★★"],
  ["자동 전투 버튼이 없는 화면","SYSTEM","사내 유일. 그 자체가 차별 소재","★★★★★"],
  ["저채도 실사 톤","COLOR","드라마 색보정 계승. 저판타지","★★★★☆"],
  ["티레 가문 문장","SYMBOL","게임 오리지널이라 IP 저촉 위험이 낮다","★★★★☆"],
  ["피의 결혼식","SYMBOL","서사의 출발점. 단어 하나로 상황이 설명된다","★★★★☆"]],
 heat:[
  {n:"플레이어 (티레 가문 서자)", role:"주인공", heat:"★★★★☆", vis:"★★★★☆", ua:"★★★★★", sns:"★★★☆☆",
   why:"⭐ 게임 오리지널 캐릭터. 원작에 없는 인물이라 표현 자유도가 상대적으로 높다",
   scene:"눈 덮인 폐허 영지에서 무너진 가문 깃발 앞에 홀로 선 모습",
   rel:"스타크 가문에 충성했던 북부 기사 가문의 서자", line:"—", nick:"—",
   now:"⭐ 크리에이티브 무게중심을 여기에 둔다", basis:"OFFICIAL — 공식 설정"},
  {n:"존 스노우", role:"드라마 인물", heat:"★★★★★", vis:"★★★★★", ua:"NOT ENOUGH PUBLIC DATA", sns:"NOT ENOUGH PUBLIC DATA",
   why:"드라마 최고 인지도 인물 중 하나. 서자라는 신분이 플레이어와 겹친다",
   scene:"장벽 너머 위협을 발견", rel:"플레이어 서사와 연결", line:"—", nick:"—",
   now:"⚠ 게임 내 등장 범위·비중 공식 확인 필요. 배우 초상권 영역",
   basis:"MEDIA — 서사 연결만 확인"},
  {n:"그 외 드라마 등장인물", role:"—", heat:"NOT ENOUGH PUBLIC DATA", vis:"★★★★☆", ua:"NOT ENOUGH PUBLIC DATA", sns:"NOT ENOUGH PUBLIC DATA",
   why:"시즌 4 시점의 인물들", scene:"—", rel:"—", line:"—", nick:"—",
   now:"⚠ 등장 여부·표현 범위 내부 자료 필요", basis:"UNVERIFIED"}],
 vdna:[
  ["저판타지","마법은 희귀하고 갈등은 인간의 정치에서 나온다","무게 · 현실감","⭐ 사내 판타지 타이틀과 결정적으로 다른 지점. 화려한 이펙트는 IP 훼손"],
  ["저채도 실사 톤","드라마 색보정","차가움 · 명예","회색·갈색·눈의 흰색. 애니 렌더링 금지"],
  ["웨스테로스 지형","드라마가 만든 공간","소속 · 몰입","북부의 눈, 장벽, 성채. 드라마 팬의 진입 동기"],
  ["가문 문장","혈통과 소속의 표식","정체성","오리지널 가문(티레)은 원작 저촉 위험이 낮아 AI 활용 가능"],
  ["자동 전투 부재","직접 조작한다","몰입 · 신뢰","사내 유일. 다른 모바일 RPG와 나란히 놓았을 때 차별점이 드러난다"]],
 fanLang:[
  {t:"웨스테로스", risk:"safe", origin:"드라마 대륙 이름", when:"드라마 방영기",
   why:"드라마 팬의 공통 어휘", now:"상시", use:"자유 사용", src:"OFFICIAL"},
  {t:"피의 결혼식", risk:"safe", origin:"드라마에서 스타크 가문이 몰살당한 사건",
   when:"드라마 방영기", why:"시리즈 최대 충격 장면 중 하나",
   now:"⭐ 이 단어 하나로 플레이어의 상황이 설명된다", use:"서사 출발점 소구에 활용", src:"OFFICIAL"},
  {t:"서자", risk:"safe", origin:"정식 혼인 밖에서 태어난 자식. 상속권도 명예도 없는 신분",
   when:"드라마 방영기 (존 스노우가 대표)", why:"밑바닥에서 시작한다는 전제",
   now:"플레이어의 신분", use:"원작 팬은 이 단어에서 존 스노우를 떠올린다", src:"OFFICIAL"},
  {t:"뽑기 없음 / 풀 수동", risk:"safe", origin:"개발진이 공식 인터뷰에서 밝힌 설계",
   when:"2026.05 출시 전", why:"모바일 RPG 관행을 벗어난 결정",
   now:"⭐ 사내에서 이 카드를 쓸 수 있는 유일한 타이틀",
   use:"⚠ 현행 상품 구성 확인 후 문구 확정. 사실과 어긋나면 불신을 키운다", src:"OFFICIAL"},
  {t:"과금 논란", risk:"caution", origin:"출시 직후 Steam 부정 평가 26%의 주된 사유",
   when:"2026.05 출시 직후", why:"EXP팩 등 상품 구성에 대한 비판",
   now:"개발사가 5.21부터 EXP팩 무료 전환, 유사 상품 미판매 발표",
   use:"대응 이력은 커뮤니케이션 자산으로 쓸 수 있으나 과장 금지", src:"COMMUNITY SIGNAL"}],
 landmine:[
  {t:"드라마 인물 임의 등장 / 배우 초상", lv:"CRITICAL", d:"HBO IP 가이드 + 배우 초상권",
   why:"⭐ 사내 12개 중 IP 제약이 가장 강하다. AI 인물 생성·실사화 모두 금지", src:"OFFICIAL"},
  {t:"화려한 판타지 이펙트·마법 남발", lv:"CRITICAL", d:"저판타지 IP와 정면 충돌",
   why:"레이븐2·뱀피르 같은 하이 판타지 문법을 가져오면 원작 팬이 즉시 이질감을 느낀다", src:"OFFICIAL"},
  {t:"드라마 영상을 게임 화면처럼 편집", lv:"HIGH", d:"과장 광고 + IP 권리 문제",
   why:"인게임 화면과 명확히 구분해야 한다", src:"OFFICIAL"},
  {t:"과금 구조를 애매하게 표현", lv:"HIGH", d:"이미 논란이 있었다",
   why:"애매하면 불신을 키운다. '유료 뽑기 없음'을 사실 그대로 명확히", src:"COMMUNITY SIGNAL"},
  {t:"애니 스타일 렌더링", lv:"MEDIUM", d:"드라마 IP의 톤이 아니다",
   why:"사실적 렌더링 유지", src:"OFFICIAL"},
  {t:"원작 대사 인용", lv:"HIGH", d:"\"겨울은 오고 있다\" 등",
   why:"⚠ IP 승인 필요. 확인 전 사용 금지", src:"UNVERIFIED"}],
 origIP:{
  memory:"HBO 드라마 「왕좌의 게임」. 조지 R. R. 마틴 소설 기반. 웨스테로스, 가문 정치, 피의 결혼식, 존 스노우, 장벽. <b>저(低)판타지</b> — 마법과 용이 있지만 희귀하고 대부분의 갈등은 인간의 정치와 폭력에서 나온다.",
  game:"드라마 시즌 4 후반부 배경. 플레이어는 스타크 가문에 충성한 북부 기사 가문 <b>티레(Tyre)의 서자</b> — 게임 오리지널 가문. 피의 결혼식에서 형제를 모두 잃은 유일한 후계자. 오리지널 스토리로 드라마의 이면을 다룬다. 유료 뽑기 없음, 100% 수동 전투.",
  gap:"⭐ 오리지널 가문을 만든 이유 — 대가문에 묶이면 여러 세력과 자유롭게 교류할 수 없다. 어느 편에도 설 수 있는 위치를 확보하기 위한 설계다.",
  sens:"드라마 인물 표현, 배우 초상, 원작 대사 인용, 가문 문장.",
  rights:"HBO IP 가이드 미확보 — RIGHTS CHECK REQUIRED (사내 최우선)"},
 timeline:[
  {d:"2026.05.14", e:"Steam 선출시", fan:"—", mkt:"출시 첫날 동시 접속 1.7만 명", hot:true},
  {d:"출시 직후", e:"과금 논란", fan:"Steam 평가 '대체로 긍정적'(71%), 부정 26%가 과금 구조 지적", mkt:"⚠ 과금 커뮤니케이션의 민감도를 보여준 사건", hot:true},
  {d:"2026.05.21", e:"모바일 출시 + 즉각 대응", fan:"EXP팩 무료 전환 발표에 반응", mkt:"⭐ 유저 반응에 빠르게 움직인 사례 — 커뮤니케이션 자산", hot:true},
  {d:"이후", e:"평가 상승", fan:"Steam 유저 평가 '매우 긍정적'으로 전환", mkt:"그래픽·스토리 몰입감이 호평의 중심", hot:true}],
 mktHistory:"과금 논란 → EXP팩 무료 전환(2026.05.21) 대응 사례 확인. UA·브랜드 필름 등은 NOT ENOUGH PUBLIC DATA",
 starter:{
  ua:{char:"플레이어(티레 가문 서자)", hook:"드라마가 비추지 않은 자리 — 유명 장면 구도를 보여주다 카메라를 옆으로 돌리면 거기 플레이어가 있다",
   sit:"눈 덮인 북부의 폐허 영지", world:"시즌 4 시점의 웨스테로스", fantasy:"BELONGING TO THE WORLD",
   sec3:"무너진 가문 깃발 앞에 홀로 선 서자",
   avoid:"화려한 마법 / 드라마 영상 오용 / 드라마 인물 임의 등장 / 과금 애매 표현"},
  banner:{hero:"플레이어 실루엣", sym:"티레 가문 문장", copy:"가문 · 명예 · 서자 · 겨울 · 맹세",
   bg:"북부의 눈·성채", trigger:"저채도 실사 톤"},
  sns:{meme:"NOT ENOUGH PUBLIC DATA — 원작 톤이 무거워 밈 상성 낮음",
   rel:"플레이어 ↔ 여러 가문", lang:"웨스테로스 · 피의 결혼식 · 서자",
   idea:"⚠ 원작 대사·밈 활용은 IP 승인 필요"},
  promo:{hero:"눈 덮인 북부 원경", world:"웨스테로스 가문 지도", motif:"가문 문장이 새겨지는 인터랙션",
   scroll:"북부 → 남부 종주", motion:"눈보라"},
  ai:{keep:"저판타지 · 저채도 자연광 · 중세 사실주의", char:"⛔ 인물 생성 절대 금지 — 배우 초상권. 실사화도 금지",
   world:"⚠ 북부 날씨·지형 무드 (인물 미포함 조건). 드라마 촬영지와 유사해지지 않도록",
   avoid:"화려한 마법 이펙트 · 애니 렌더링 · 밝고 경쾌한 톤 · generic fantasy 갑옷"}},
 sources:[["공식 사이트 gameofthrones.netmarble.com","OFFICIAL"],["ZDNet — 문준기 인터뷰(확률형 제외·100% 수동)","OFFICIAL"],
  ["게임뷰 — 오리지널 스토리 질의응답","MEDIA"],["인벤 — 5월 14일 정식 론칭","MEDIA"],
  ["ZDNet — Steam 첫날 동접 1.7만","MEDIA"],["경향게임스 — Steam 평가·과금 비판","MEDIA"],
  ["디시인사이드 — EXP팩 무료 전환","COMMUNITY SIGNAL"],["나무위키 — 티레 가문 서자 설정","COMMUNITY SIGNAL"]],
 gaps:["HBO IP 가이드 (사내 최우선 · RIGHTS CHECK REQUIRED)","드라마 인물 게임 내 등장 범위","드라마 영상·대사 사용권 · 배우 초상 제약","현행 상품 구성 (과금 문구 확정에 필요)","게임 내 개방 지역 구성","유저 데이터"]
},

{
 id:"shangri", no:"13", name:"샹그릴라 프론티어: 일곱 최강종", short:"샹그릴라 프론티어",
 ipClass:"LICENSED", genre:"RPG", status:"UNRELEASED", maturity:"LOW",
 dev:"넷마블 넥서스", release:"2026 예정", plat:"모바일", region:"일본 티저 공개",
 sw:["#2E4A6B","#4A8FA8","#7BC4B0","#E8D9A0"],
 asset:"UNKNOWN", assetNote:"NOT ENOUGH PUBLIC DATA — 게임 고유 정보가 거의 없다",
 one:"「샹그릴라 프론티어」 IP 기반 RPG. 게임 고유 정보는 일본 티저 수준으로만 공개됨.",
 coreFantasy:{code:"MASTERY (추정)", flow:["망겜 경험","공략 지식","강적","도전","돌파"],
   desc:"⚠ 원작 구조 기반 <b>추정</b>이다. 원작은 '망겜 헌터'가 갓겜에 도전하는 구조로, <b>게임을 누구보다 잘 이해하는 플레이어가 압도적인 강적을 공략한다</b>는 플레이어 판타지를 갖는다. 게임 버전이 이를 어떻게 구현했는지는 미확인."},
 iconic5:[["NOT ENOUGH PUBLIC DATA","—","게임 고유 시각 자산 미공개 — 티저 단계","—"]],
 heat:[{n:"NOT ENOUGH PUBLIC DATA", role:"—", heat:"—", vis:"—", ua:"—", sns:"—",
   why:"게임 내 플레이어블 캐릭터 구성 미공개", scene:"—", rel:"—", line:"—", nick:"—",
   now:"⚠ 원작 캐릭터(산라쿠·에무르 등)의 게임 내 구현 여부 미확인", basis:"UNVERIFIED"}],
 vdna:[["NOT ENOUGH PUBLIC DATA","—","—","게임 비주얼 가이드 미공개. 원작 애니 톤 참조는 가능하나 게임 적용 여부 미확인"]],
 fanLang:[{t:"NOT ENOUGH PUBLIC DATA", risk:"caution", origin:"—", when:"—",
   why:"원작 팬덤 언어는 존재하나 게임 맥락에서의 사용 가부 미확인", now:"—",
   use:"⚠ 원작 팬덤 조사 필요", src:"UNVERIFIED"}],
 landmine:[
  {t:"원작 정보로 게임 팩트북을 채우는 것", lv:"CRITICAL",
   d:"원작 만화·애니 정보는 풍부하나 게임 고유 정보가 거의 없다",
   why:"⭐ 원작 정보를 게임 정보처럼 쓰면 실제 게임과 다른 기대를 만든다. 출시 후 광고와 실물의 괴리로 이어진다", src:"OFFICIAL"},
  {t:"원작 명장면·명대사 임의 사용", lv:"HIGH", d:"고단샤 라이선스 IP",
   why:"게임에 구현되지 않은 요소를 광고에 쓰면 과장 광고", src:"UNVERIFIED"}],
 origIP:{
  memory:"⚠ 원작 「샹그릴라 프론티어 ~망겜 헌터, 갓겜에 도전하다~」. 소설가가 되자 연재(2017.05~) → 고단샤 「주간 소년 매거진」 만화 연재(2020.07~) → 애니메이션화. 일본 웹소설 누적 9억 조회, 만화 누적 1,300만 부 이상. 상세 캐릭터·장면·밈은 미조사.",
  game:"「샹그릴라 프론티어: 일곱 최강종」. 넷마블 넥서스 개발. 2026년 출시 예정. 일본 공식 티저 사이트 오픈 및 PV 공개. <b>그 외 게임 고유 정보 미공개.</b>",
  gap:"NOT ENOUGH PUBLIC DATA — 원작 팬 기대와 게임 표현의 차이를 판단할 자료 없음",
  sens:"NOT ENOUGH PUBLIC DATA",
  rights:"고단샤 IP 가이드 미확보 — RIGHTS CHECK REQUIRED"},
 timeline:[
  {d:"2017.05", e:"원작 웹소설 연재 시작", fan:"일본 누적 9억 조회", mkt:"IP 규모의 근거", hot:false},
  {d:"2020.07", e:"주간 소년 매거진 만화 연재", fan:"누적 1,300만 부 이상", mkt:"—", hot:false},
  {d:"—", e:"애니메이션화", fan:"—", mkt:"—", hot:false},
  {d:"2026 예정", e:"넷마블 게임 출시 예정", fan:"—", mkt:"⚠ 일본 티저 사이트·PV 공개 단계", hot:false}],
 mktHistory:"NOT ENOUGH PUBLIC DATA",
 starter:{
  ua:{char:"NOT ENOUGH PUBLIC DATA", hook:"—", sit:"—", world:"—", fantasy:"MASTERY (추정)",
   sec3:"—", avoid:"⚠ 원작 정보를 게임 정보처럼 사용하는 것"},
  banner:{hero:"NOT ENOUGH PUBLIC DATA", sym:"—", copy:"—", bg:"—", trigger:"—"},
  sns:{meme:"NOT ENOUGH PUBLIC DATA", rel:"—", lang:"—", idea:"—"},
  promo:{hero:"NOT ENOUGH PUBLIC DATA", world:"—", motif:"—", scroll:"—", motion:"—"},
  ai:{keep:"NOT ENOUGH PUBLIC DATA — 게임 비주얼 가이드 미공개", char:"⛔ 생성 금지",
   world:"—", avoid:"원작 애니 스틸을 게임 화면처럼 사용"}},
 sources:[["루리웹 — 일본 티저 사이트 오픈·PV 공개","MEDIA"],["위키백과 — 원작 연재 정보","MEDIA"],
  ["Wikipedia — Shangri-La Frontier","MEDIA"]],
 gaps:["게임 고유 정보 전반 (플레이 방식·캐릭터·시스템)","한국/글로벌 출시 계획","원작 캐릭터의 게임 내 구현 범위","고단샤 IP 가이드 (RIGHTS CHECK REQUIRED)","원작 팬덤 언어·밈 조사","정식 타이틀명 최종 확인"]
},

{
 id:"octopus", no:"14", name:"프로젝트 옥토퍼스", short:"프로젝트 옥토퍼스",
 ipClass:"EXT_PUB", genre:"캐주얼 액션 로그라이크 RPG", status:"UNRELEASED", maturity:"LOW",
 dev:"콩스튜디오 (넷마블 퍼블리싱)", release:"2026 예정", plat:"미공개", region:"글로벌 판권 확보",
 sw:["#3A4A5C","#5C7A8A","#8AA8B0","#D4C4A8"],
 asset:"UNKNOWN", assetNote:"NOT ENOUGH PUBLIC DATA — 개발 코드명 단계",
 one:"콩스튜디오가 개발하고 넷마블이 글로벌 퍼블리싱하는 도트 그래픽 기반 캐주얼 액션 로그라이크 RPG.",
 coreFantasy:{code:"NOT ENOUGH PUBLIC DATA", flow:[],
   desc:"⚠ 개발 코드명 단계로, Core Fantasy를 정의할 근거가 없다. <b>추측하지 않는다.</b>"},
 iconic5:[["NOT ENOUGH PUBLIC DATA","—","시각 자산 미공개","—"]],
 heat:[{n:"NOT ENOUGH PUBLIC DATA", role:"—", heat:"—", vis:"—", ua:"—", sns:"—",
   why:"캐릭터 구성 미공개", scene:"—", rel:"—", line:"—", nick:"—", now:"—", basis:"UNVERIFIED"}],
 vdna:[["도트 그래픽 (확인)","—","—","⚠ 도트 기반이라는 것만 확인. 구체적 아트 디렉션 미공개"]],
 fanLang:[{t:"NOT ENOUGH PUBLIC DATA", risk:"caution", origin:"—", when:"—",
   why:"미출시로 팬덤 형성 전", now:"—", use:"—", src:"UNVERIFIED"}],
 landmine:[
  {t:"미공개 프로젝트를 기존 IP와 연결짓는 것", lv:"HIGH",
   d:"⚠ 「가디언 테일즈」 IP 활용 여부는 매체 언급만 있고 공식 확인되지 않았다",
   why:"확인되지 않은 IP 연결을 광고에 쓰면 권리 문제와 기대 불일치가 동시에 발생", src:"UNVERIFIED"}],
 origIP:{
  memory:"NOT ENOUGH PUBLIC DATA — 개발사 콩스튜디오는 「던전링크」·「가디언 테일즈」로 알려져 있으나, 본 프로젝트와의 IP 관계는 공식 확인되지 않음",
  game:"넷마블이 2025.11 글로벌 퍼블리싱 계약 체결. 도트 그래픽 기반 캐주얼 액션 로그라이크 RPG. '광산'을 배경으로 다양한 콘텐츠 예정. 간편한 조작으로 다양한 전투 빌드 구성.",
  gap:"NOT ENOUGH PUBLIC DATA",
  sens:"NOT ENOUGH PUBLIC DATA",
  rights:"개발사·IP 권리 관계 미확인 — RIGHTS CHECK REQUIRED"},
 timeline:[
  {d:"2025.11", e:"넷마블 글로벌 퍼블리싱 계약 체결", fan:"—", mkt:"국내외 서비스 판권 확보", hot:false},
  {d:"2026 예정", e:"출시 예정", fan:"—", mkt:"⚠ 정식 명칭·출시일 미정", hot:false}],
 mktHistory:"NOT ENOUGH PUBLIC DATA",
 starter:{
  ua:{char:"NOT ENOUGH PUBLIC DATA", hook:"—", sit:"—", world:"—", fantasy:"—",
   sec3:"—", avoid:"⚠ 확인되지 않은 IP 연결"},
  banner:{hero:"NOT ENOUGH PUBLIC DATA", sym:"—", copy:"—", bg:"—", trigger:"—"},
  sns:{meme:"NOT ENOUGH PUBLIC DATA", rel:"—", lang:"—", idea:"—"},
  promo:{hero:"NOT ENOUGH PUBLIC DATA", world:"—", motif:"—", scroll:"—", motion:"—"},
  ai:{keep:"NOT ENOUGH PUBLIC DATA", char:"⛔ 생성 금지", world:"—", avoid:"—"}},
 sources:[["ZDNet·전자신문 — 글로벌 퍼블리싱 계약 체결","MEDIA"],
  ["글로벌이코노믹 — 옥토퍼스 미리보기","MEDIA"]],
 gaps:["정식 타이틀명","출시일·플랫폼","게임플레이 상세","IP 권리 관계 (가디언 테일즈 연관 여부)","캐릭터·세계관 전반","⚠ 내부 자료 없이는 팩트북 작성 불가"]
}
];
